# Generated by Django 3.2 on 2021-05-09 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_advisor_calls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.advisor'),
        ),
        migrations.AlterField(
            model_name='calls',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
