# Generated by Django 3.2 on 2021-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210509_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
